import { ArrowRight, BookOpenCheck, CalendarDays, CircleCheck } from "lucide-react";
import { useTranslations } from "next-intl";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Link } from "@/i18n/navigation";

export function StudyCaveHomeworkPanel() {
  const t = useTranslations("studyCave.homeworkPanel");
  return <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_20rem]" data-testid="study-cave-homework-panel"><Card className="shadow-surface"><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><BookOpenCheck className="size-5 text-primary" />{t("title")}</CardTitle><CardDescription className="mt-1">{t("description")}</CardDescription></div><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-semibold text-secondary-foreground">{t("status")}</span></div></CardHeader><CardContent><div className="rounded-xl border border-border bg-secondary/35 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{t("assignment")}</strong><span className="flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="size-3.5" />{t("due")}</span></div><p className="mt-1 text-sm text-muted-foreground">{t("subject")}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-card"><span className="block h-full w-3/5 rounded-full bg-primary" /></div><p className="mt-2 text-xs font-medium text-muted-foreground">{t("progress")}</p></div><Link href="/student/homework/action-reaction" className={buttonVariants({ size: "lg", className: "mt-4 w-full" })}>{t("open")}<ArrowRight className="rtl:-scale-x-100" /></Link></CardContent></Card><Card className="border-assistant bg-assistant/35 shadow-surface"><CardHeader><CardTitle>{t("next.title")}</CardTitle><CardDescription>{t("next.description")}</CardDescription></CardHeader><CardContent><ul className="grid gap-3 text-sm">{["one", "two", "three"].map((key) => <li className="flex gap-2" key={key}><CircleCheck className="size-4 shrink-0 text-success-foreground" />{t(`next.${key}`)}</li>)}</ul></CardContent></Card></section>;
}
