"use client";

import { ArrowRight, BookOpenCheck, CalendarDays, ChevronRight, ClipboardList } from "lucide-react";
import { useTranslations } from "next-intl";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Link } from "@/i18n/navigation";
import { homeworkIds } from "../homework-data";

export function StudentHomeworkList() {
  const t = useTranslations("studentHomework");
  return <div className="mx-auto flex w-full max-w-270 flex-col gap-5 pb-20" data-testid="student-homework-page"><header><div className="flex items-center gap-2 text-primary"><ClipboardList className="size-4" /><span className="text-xs font-semibold">{t("list.eyebrow")}</span></div><h1 className="mt-1 font-heading text-page font-bold tracking-tight">{t("list.title")}</h1><p className="mt-1 text-sm text-muted-foreground sm:text-base">{t("list.description")}</p></header><section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_18rem]" aria-label={t("list.label")}><div className="grid gap-3">{homeworkIds.map((id) => { const assignment = `assignments.${id}`; return <Link key={id} href={`/student/homework/${id}`} className="group rounded-2xl outline-none focus-visible:ring-2 focus-visible:ring-ring"><Card className="h-full transition-colors group-hover:border-primary/45 group-hover:bg-secondary/20"><CardContent className="flex items-center gap-4 p-4 sm:p-5"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-secondary text-secondary-foreground"><BookOpenCheck className="size-5" /></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><strong className="text-base">{t(`${assignment}.title`)}</strong><span className="rounded-full bg-secondary px-2 py-1 text-xs font-semibold text-secondary-foreground">{t(`${assignment}.status`)}</span></span><span className="mt-1 block text-sm text-muted-foreground">{t(`${assignment}.subject`)} · {t(`${assignment}.description`)}</span><span className="mt-2 flex items-center gap-1 text-xs font-medium text-primary"><CalendarDays className="size-3.5" />{t(`${assignment}.due`)}</span></span><ChevronRight className="size-5 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5 rtl:-scale-x-100 rtl:group-hover:-translate-x-0.5" /></CardContent></Card></Link>; })}</div><Card className="h-fit border-assistant bg-assistant/35 shadow-surface"><CardHeader><CardTitle>{t("list.help.title")}</CardTitle><CardDescription>{t("list.help.description")}</CardDescription></CardHeader><CardContent><p className="text-sm leading-6">{t("list.help.text")}</p><div className="mt-4 flex items-center gap-2 text-sm font-semibold text-assistant-foreground"><ArrowRight className="size-4 rtl:-scale-x-100" />{t("list.help.note")}</div></CardContent></Card></section></div>;
}
